---
abstract: 'Sugar and strong errors for $c->uri_for'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  HTTP::Request::Common: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-URI
requires:
  Catalyst: '5.90060'
  Moo: '2.000002'
  Scalar::List::Utils: '1.42'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-URI/issues
  homepage: https://github.com/jjn1056/Catalyst-Plugin-URI
  repository: https://github.com/jjn1056/Catalyst-URI.git
version: '0.001'
